2020/09/06 22:49:31 [error] [exception.CException] exception 'CException' with message 'คุณสมบัติ "Project.id" ยังไม่ถูกกำหนด' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\pea_track\protected\views\project\_formUpdate.php(539): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track\protected\views\project\update.php(12): CController->renderPartial('_formUpdate', Array)
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#10 C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php(1814): CController->render('update', Array)
#11 [internal function]: ProjectController->actionUpdate('344')
#12 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ProjectController), Array)
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProjectController), Object(ReflectionMethod), Array)
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('update')
#23 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('project/update')
#24 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/pea_track/project/update/344
HTTP_REFERER=http://localhost/pea_track/project/index
---
2020/09/06 22:50:43 [error] [exception.CException] exception 'CException' with message 'คุณสมบัติ "Project.id" ยังไม่ถูกกำหนด' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\pea_track\protected\views\project\_formUpdate.php(539): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track\protected\views\project\update.php(12): CController->renderPartial('_formUpdate', Array)
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#10 C:\xampp\htdocs\pea_track\protected\controllers\ProjectController.php(1814): CController->render('update', Array)
#11 [internal function]: ProjectController->actionUpdate('344')
#12 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ProjectController), Array)
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ProjectController), Object(ReflectionMethod), Array)
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('update')
#23 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('project/update')
#24 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/pea_track/project/update/344
HTTP_REFERER=http://localhost/pea_track/project/index
---
2020/09/07 11:55:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "cancel" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(270): CController->missingAction('cancel')
#1 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('cancel')
#2 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('paymentProjectC...')
#3 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track/paymentProjectContract/cancel/73?note=
HTTP_REFERER=http://localhost/pea_track/paymentProjectContract/index
---
2020/09/07 11:55:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'ระบบไม่สามารถดำเนินการ "cancel" ตามคำสั่งได้' in C:\xampp\htdocs\pea_track\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\web\CController.php(270): CController->missingAction('cancel')
#1 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('cancel')
#2 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('paymentProjectC...')
#3 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/pea_track/paymentProjectContract/cancel/73?note=vvvvv
HTTP_REFERER=http://localhost/pea_track/paymentProjectContract/index
---
2020/09/07 12:58:14 [error] [exception.CException] exception 'CException' with message 'คุณสมบัติ "Project.proj_manager_name" ยังไม่ถูกกำหนด' in C:\xampp\htdocs\pea_track\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\pea_track\framework\db\ar\CActiveRecord.php(145): CComponent->__get('proj_manager_na...')
#1 C:\xampp\htdocs\pea_track\protected\views\paymentProjectContract\_form.php(169): CActiveRecord->__get('proj_manager_na...')
#2 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\pea_track\protected\views\paymentProjectContract\update.php(11): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\pea_track\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\pea_track\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\pea_track\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#10 C:\xampp\htdocs\pea_track\protected\controllers\PaymentProjectContractController.php(315): CController->render('update', Array)
#11 [internal function]: PaymentProjectContractController->actionUpdate('401')
#12 C:\xampp\htdocs\pea_track\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(PaymentProjectContractController), Array)
#13 C:\xampp\htdocs\pea_track\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(PaymentProjectContractController), Object(ReflectionMethod), Array)
#14 C:\xampp\htdocs\pea_track\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\pea_track\framework\web\filters\CFilter.php(40): CFilterChain->run()
#17 C:\xampp\htdocs\pea_track\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\pea_track\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#19 C:\xampp\htdocs\pea_track\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\pea_track\framework\web\CController.php(291): CFilterChain->run()
#21 C:\xampp\htdocs\pea_track\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(282): CController->run('update')
#23 C:\xampp\htdocs\pea_track\framework\web\CWebApplication.php(141): CWebApplication->runController('paymentProjectC...')
#24 C:\xampp\htdocs\pea_track\framework\base\CApplication.php(180): CWebApplication->processRequest()
#25 C:\xampp\htdocs\pea_track\index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/pea_track/paymentProjectContract/update/401
HTTP_REFERER=http://localhost/pea_track/paymentProjectContract/index
---
